// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_environments

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EnvironmentsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"environments": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "A unique identifier for the environment. If not provided, the associated environment will be treated as a newly created environment.",
							MarkdownDescription: "A unique identifier for the environment. If not provided, the associated environment will be treated as a newly created environment.",
						},
						"is_production": schema.BoolAttribute{
							Required:            true,
							Description:         "Whether the environment is production.",
							MarkdownDescription: "Whether the environment is production.",
						},
						"name": schema.StringAttribute{
							Required:            true,
							Description:         "The name of the environment.",
							MarkdownDescription: "The name of the environment.",
						},
						"required_review_group_id": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "The ID of the review group that the environment requires review from.",
							MarkdownDescription: "The ID of the review group that the environment requires review from.",
						},
						"requires_release_pipeline": schema.BoolAttribute{
							Required:            true,
							Description:         "Whether the environment requires a release pipeline.",
							MarkdownDescription: "Whether the environment requires a release pipeline.",
						},
						"requires_review": schema.BoolAttribute{
							Required:            true,
							Description:         "Whether the environment requires review.",
							MarkdownDescription: "Whether the environment requires review.",
						},
					},
					CustomType: EnvironmentsType{
						ObjectType: types.ObjectType{
							AttrTypes: EnvironmentsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required: true,
			},
		},
	}
}

type EnvironmentsModel struct {
	Environments types.List `tfsdk:"environments"`
}

var _ basetypes.ObjectTypable = EnvironmentsType{}

type EnvironmentsType struct {
	basetypes.ObjectType
}

func (t EnvironmentsType) Equal(o attr.Type) bool {
	other, ok := o.(EnvironmentsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EnvironmentsType) String() string {
	return "EnvironmentsType"
}

func (t EnvironmentsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isProductionAttribute, ok := attributes["is_production"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_production is missing from object`)

		return nil, diags
	}

	isProductionVal, ok := isProductionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_production expected to be basetypes.BoolValue, was: %T`, isProductionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	requiredReviewGroupIdAttribute, ok := attributes["required_review_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`required_review_group_id is missing from object`)

		return nil, diags
	}

	requiredReviewGroupIdVal, ok := requiredReviewGroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`required_review_group_id expected to be basetypes.StringValue, was: %T`, requiredReviewGroupIdAttribute))
	}

	requiresReleasePipelineAttribute, ok := attributes["requires_release_pipeline"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_release_pipeline is missing from object`)

		return nil, diags
	}

	requiresReleasePipelineVal, ok := requiresReleasePipelineAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_release_pipeline expected to be basetypes.BoolValue, was: %T`, requiresReleasePipelineAttribute))
	}

	requiresReviewAttribute, ok := attributes["requires_review"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_review is missing from object`)

		return nil, diags
	}

	requiresReviewVal, ok := requiresReviewAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_review expected to be basetypes.BoolValue, was: %T`, requiresReviewAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EnvironmentsValue{
		Id:                      idVal,
		IsProduction:            isProductionVal,
		Name:                    nameVal,
		RequiredReviewGroupId:   requiredReviewGroupIdVal,
		RequiresReleasePipeline: requiresReleasePipelineVal,
		RequiresReview:          requiresReviewVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewEnvironmentsValueNull() EnvironmentsValue {
	return EnvironmentsValue{
		state: attr.ValueStateNull,
	}
}

func NewEnvironmentsValueUnknown() EnvironmentsValue {
	return EnvironmentsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEnvironmentsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EnvironmentsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EnvironmentsValue Attribute Value",
				"While creating a EnvironmentsValue value, a missing attribute value was detected. "+
					"A EnvironmentsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnvironmentsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EnvironmentsValue Attribute Type",
				"While creating a EnvironmentsValue value, an invalid attribute value was detected. "+
					"A EnvironmentsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnvironmentsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EnvironmentsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EnvironmentsValue Attribute Value",
				"While creating a EnvironmentsValue value, an extra attribute value was detected. "+
					"A EnvironmentsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EnvironmentsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEnvironmentsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isProductionAttribute, ok := attributes["is_production"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_production is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	isProductionVal, ok := isProductionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_production expected to be basetypes.BoolValue, was: %T`, isProductionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	requiredReviewGroupIdAttribute, ok := attributes["required_review_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`required_review_group_id is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	requiredReviewGroupIdVal, ok := requiredReviewGroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`required_review_group_id expected to be basetypes.StringValue, was: %T`, requiredReviewGroupIdAttribute))
	}

	requiresReleasePipelineAttribute, ok := attributes["requires_release_pipeline"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_release_pipeline is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	requiresReleasePipelineVal, ok := requiresReleasePipelineAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_release_pipeline expected to be basetypes.BoolValue, was: %T`, requiresReleasePipelineAttribute))
	}

	requiresReviewAttribute, ok := attributes["requires_review"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`requires_review is missing from object`)

		return NewEnvironmentsValueUnknown(), diags
	}

	requiresReviewVal, ok := requiresReviewAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`requires_review expected to be basetypes.BoolValue, was: %T`, requiresReviewAttribute))
	}

	if diags.HasError() {
		return NewEnvironmentsValueUnknown(), diags
	}

	return EnvironmentsValue{
		Id:                      idVal,
		IsProduction:            isProductionVal,
		Name:                    nameVal,
		RequiredReviewGroupId:   requiredReviewGroupIdVal,
		RequiresReleasePipeline: requiresReleasePipelineVal,
		RequiresReview:          requiresReviewVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewEnvironmentsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EnvironmentsValue {
	object, diags := NewEnvironmentsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEnvironmentsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EnvironmentsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEnvironmentsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEnvironmentsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEnvironmentsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEnvironmentsValueMust(EnvironmentsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EnvironmentsType) ValueType(ctx context.Context) attr.Value {
	return EnvironmentsValue{}
}

var _ basetypes.ObjectValuable = EnvironmentsValue{}

type EnvironmentsValue struct {
	Id                      basetypes.StringValue `tfsdk:"id"`
	IsProduction            basetypes.BoolValue   `tfsdk:"is_production"`
	Name                    basetypes.StringValue `tfsdk:"name"`
	RequiredReviewGroupId   basetypes.StringValue `tfsdk:"required_review_group_id"`
	RequiresReleasePipeline basetypes.BoolValue   `tfsdk:"requires_release_pipeline"`
	RequiresReview          basetypes.BoolValue   `tfsdk:"requires_review"`
	state                   attr.ValueState
}

func (v EnvironmentsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_production"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["required_review_group_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["requires_release_pipeline"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["requires_review"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IsProduction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_production"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.RequiredReviewGroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["required_review_group_id"] = val

		val, err = v.RequiresReleasePipeline.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["requires_release_pipeline"] = val

		val, err = v.RequiresReview.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["requires_review"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EnvironmentsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EnvironmentsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EnvironmentsValue) String() string {
	return "EnvironmentsValue"
}

func (v EnvironmentsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"id":                        basetypes.StringType{},
			"is_production":             basetypes.BoolType{},
			"name":                      basetypes.StringType{},
			"required_review_group_id":  basetypes.StringType{},
			"requires_release_pipeline": basetypes.BoolType{},
			"requires_review":           basetypes.BoolType{},
		},
		map[string]attr.Value{
			"id":                        v.Id,
			"is_production":             v.IsProduction,
			"name":                      v.Name,
			"required_review_group_id":  v.RequiredReviewGroupId,
			"requires_release_pipeline": v.RequiresReleasePipeline,
			"requires_review":           v.RequiresReview,
		})

	return objVal, diags
}

func (v EnvironmentsValue) Equal(o attr.Value) bool {
	other, ok := o.(EnvironmentsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IsProduction.Equal(other.IsProduction) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.RequiredReviewGroupId.Equal(other.RequiredReviewGroupId) {
		return false
	}

	if !v.RequiresReleasePipeline.Equal(other.RequiresReleasePipeline) {
		return false
	}

	if !v.RequiresReview.Equal(other.RequiresReview) {
		return false
	}

	return true
}

func (v EnvironmentsValue) Type(ctx context.Context) attr.Type {
	return EnvironmentsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EnvironmentsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":                        basetypes.StringType{},
		"is_production":             basetypes.BoolType{},
		"name":                      basetypes.StringType{},
		"required_review_group_id":  basetypes.StringType{},
		"requires_release_pipeline": basetypes.BoolType{},
		"requires_review":           basetypes.BoolType{},
	}
}
