// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tag

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(1000),
				},
			},
			"is_core": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "id",
				MarkdownDescription: "id",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 100),
				},
			},
		},
	}
}

type TagModel struct {
	Description types.String `tfsdk:"description"`
	IsCore      types.Bool   `tfsdk:"is_core"`
	Name        types.String `tfsdk:"name"`
}
