// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_entity_property

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EntityPropertyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional detailed context for the entity property source.",
				MarkdownDescription: "Optional detailed context for the entity property source.",
			},
			"id_type_mapping": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"column": schema.StringAttribute{
							Required:            true,
							Description:         "Column name linked to the ID.",
							MarkdownDescription: "Column name linked to the ID.",
						},
						"statsig_unit_id": schema.StringAttribute{
							Required:            true,
							Description:         "ID for the Statsig unit.",
							MarkdownDescription: "ID for the Statsig unit.",
						},
					},
					CustomType: IdTypeMappingType{
						ObjectType: types.ObjectType{
							AttrTypes: IdTypeMappingValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "Mappings of Statsig units to their columns.",
				MarkdownDescription: "Mappings of Statsig units to their columns.",
			},
			"is_read_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Specifies if the source can only be edited via the Console API.",
				MarkdownDescription: "Specifies if the source can only be edited via the Console API.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Unique identifier for the entity property source.",
				MarkdownDescription: "Unique identifier for the entity property source.",
			},
			"owner": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"owner_email": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The email of the owner. This field is optional.",
						MarkdownDescription: "The email of the owner. This field is optional.",
					},
					"owner_id": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "ID of the owner",
						MarkdownDescription: "ID of the owner",
					},
					"owner_name": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The name of the owner. This field is optional.",
						MarkdownDescription: "The name of the owner. This field is optional.",
					},
					"owner_type": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Type of the owner (e.g., SDK_KEY or USER)",
						MarkdownDescription: "Type of the owner (e.g., SDK_KEY or USER)",
					},
				},
				CustomType: OwnerType{
					ObjectType: types.ObjectType{
						AttrTypes: OwnerValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Schema for owner data including ID, type, name. Note that if Entity is created by CONSOLE API, owner will be undefined.",
				MarkdownDescription: "Schema for owner data including ID, type, name. Note that if Entity is created by CONSOLE API, owner will be undefined.",
			},
			"sql": schema.StringAttribute{
				Required:            true,
				Description:         "SQL query defining the data source.",
				MarkdownDescription: "SQL query defining the data source.",
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Optional tags for categorization.",
				MarkdownDescription: "Optional tags for categorization.",
			},
			"timestamp_as_day": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Indicates if the timestamp is treated as a day.",
				MarkdownDescription: "Indicates if the timestamp is treated as a day.",
			},
			"timestamp_column": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Optional column name for timestamp.",
				MarkdownDescription: "Optional column name for timestamp.",
			},
		},
	}
}

type EntityPropertyModel struct {
	Description     types.String `tfsdk:"description"`
	IdTypeMapping   types.List   `tfsdk:"id_type_mapping"`
	IsReadOnly      types.Bool   `tfsdk:"is_read_only"`
	Name            types.String `tfsdk:"name"`
	Owner           OwnerValue   `tfsdk:"owner"`
	Sql             types.String `tfsdk:"sql"`
	Tags            types.List   `tfsdk:"tags"`
	TimestampAsDay  types.Bool   `tfsdk:"timestamp_as_day"`
	TimestampColumn types.String `tfsdk:"timestamp_column"`
}

var _ basetypes.ObjectTypable = IdTypeMappingType{}

type IdTypeMappingType struct {
	basetypes.ObjectType
}

func (t IdTypeMappingType) Equal(o attr.Type) bool {
	other, ok := o.(IdTypeMappingType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IdTypeMappingType) String() string {
	return "IdTypeMappingType"
}

func (t IdTypeMappingType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	columnAttribute, ok := attributes["column"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`column is missing from object`)

		return nil, diags
	}

	columnVal, ok := columnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`column expected to be basetypes.StringValue, was: %T`, columnAttribute))
	}

	statsigUnitIdAttribute, ok := attributes["statsig_unit_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`statsig_unit_id is missing from object`)

		return nil, diags
	}

	statsigUnitIdVal, ok := statsigUnitIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`statsig_unit_id expected to be basetypes.StringValue, was: %T`, statsigUnitIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IdTypeMappingValue{
		Column:        columnVal,
		StatsigUnitId: statsigUnitIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewIdTypeMappingValueNull() IdTypeMappingValue {
	return IdTypeMappingValue{
		state: attr.ValueStateNull,
	}
}

func NewIdTypeMappingValueUnknown() IdTypeMappingValue {
	return IdTypeMappingValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIdTypeMappingValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IdTypeMappingValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IdTypeMappingValue Attribute Value",
				"While creating a IdTypeMappingValue value, a missing attribute value was detected. "+
					"A IdTypeMappingValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IdTypeMappingValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IdTypeMappingValue Attribute Type",
				"While creating a IdTypeMappingValue value, an invalid attribute value was detected. "+
					"A IdTypeMappingValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IdTypeMappingValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IdTypeMappingValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IdTypeMappingValue Attribute Value",
				"While creating a IdTypeMappingValue value, an extra attribute value was detected. "+
					"A IdTypeMappingValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IdTypeMappingValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIdTypeMappingValueUnknown(), diags
	}

	columnAttribute, ok := attributes["column"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`column is missing from object`)

		return NewIdTypeMappingValueUnknown(), diags
	}

	columnVal, ok := columnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`column expected to be basetypes.StringValue, was: %T`, columnAttribute))
	}

	statsigUnitIdAttribute, ok := attributes["statsig_unit_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`statsig_unit_id is missing from object`)

		return NewIdTypeMappingValueUnknown(), diags
	}

	statsigUnitIdVal, ok := statsigUnitIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`statsig_unit_id expected to be basetypes.StringValue, was: %T`, statsigUnitIdAttribute))
	}

	if diags.HasError() {
		return NewIdTypeMappingValueUnknown(), diags
	}

	return IdTypeMappingValue{
		Column:        columnVal,
		StatsigUnitId: statsigUnitIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewIdTypeMappingValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IdTypeMappingValue {
	object, diags := NewIdTypeMappingValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIdTypeMappingValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IdTypeMappingType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIdTypeMappingValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIdTypeMappingValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIdTypeMappingValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIdTypeMappingValueMust(IdTypeMappingValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IdTypeMappingType) ValueType(ctx context.Context) attr.Value {
	return IdTypeMappingValue{}
}

var _ basetypes.ObjectValuable = IdTypeMappingValue{}

type IdTypeMappingValue struct {
	Column        basetypes.StringValue `tfsdk:"column"`
	StatsigUnitId basetypes.StringValue `tfsdk:"statsig_unit_id"`
	state         attr.ValueState
}

func (v IdTypeMappingValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["column"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["statsig_unit_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Column.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["column"] = val

		val, err = v.StatsigUnitId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["statsig_unit_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IdTypeMappingValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IdTypeMappingValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IdTypeMappingValue) String() string {
	return "IdTypeMappingValue"
}

func (v IdTypeMappingValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"column":          basetypes.StringType{},
			"statsig_unit_id": basetypes.StringType{},
		},
		map[string]attr.Value{
			"column":          v.Column,
			"statsig_unit_id": v.StatsigUnitId,
		})

	return objVal, diags
}

func (v IdTypeMappingValue) Equal(o attr.Value) bool {
	other, ok := o.(IdTypeMappingValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Column.Equal(other.Column) {
		return false
	}

	if !v.StatsigUnitId.Equal(other.StatsigUnitId) {
		return false
	}

	return true
}

func (v IdTypeMappingValue) Type(ctx context.Context) attr.Type {
	return IdTypeMappingType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IdTypeMappingValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"column":          basetypes.StringType{},
		"statsig_unit_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OwnerType{}

type OwnerType struct {
	basetypes.ObjectType
}

func (t OwnerType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerType) String() string {
	return "OwnerType"
}

func (t OwnerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	ownerEmailAttribute, ok := attributes["owner_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_email is missing from object`)

		return nil, diags
	}

	ownerEmailVal, ok := ownerEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_email expected to be basetypes.StringValue, was: %T`, ownerEmailAttribute))
	}

	ownerIdAttribute, ok := attributes["owner_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_id is missing from object`)

		return nil, diags
	}

	ownerIdVal, ok := ownerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_id expected to be basetypes.StringValue, was: %T`, ownerIdAttribute))
	}

	ownerNameAttribute, ok := attributes["owner_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_name is missing from object`)

		return nil, diags
	}

	ownerNameVal, ok := ownerNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_name expected to be basetypes.StringValue, was: %T`, ownerNameAttribute))
	}

	ownerTypeAttribute, ok := attributes["owner_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_type is missing from object`)

		return nil, diags
	}

	ownerTypeVal, ok := ownerTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_type expected to be basetypes.StringValue, was: %T`, ownerTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerValue{
		OwnerEmail: ownerEmailVal,
		OwnerId:    ownerIdVal,
		OwnerName:  ownerNameVal,
		OwnerType:  ownerTypeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueNull() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerValueUnknown() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerValue Attribute Value",
				"While creating a OwnerValue value, a missing attribute value was detected. "+
					"A OwnerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerValue Attribute Type",
				"While creating a OwnerValue value, an invalid attribute value was detected. "+
					"A OwnerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerValue Attribute Value",
				"While creating a OwnerValue value, an extra attribute value was detected. "+
					"A OwnerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	ownerEmailAttribute, ok := attributes["owner_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_email is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	ownerEmailVal, ok := ownerEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_email expected to be basetypes.StringValue, was: %T`, ownerEmailAttribute))
	}

	ownerIdAttribute, ok := attributes["owner_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_id is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	ownerIdVal, ok := ownerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_id expected to be basetypes.StringValue, was: %T`, ownerIdAttribute))
	}

	ownerNameAttribute, ok := attributes["owner_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_name is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	ownerNameVal, ok := ownerNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_name expected to be basetypes.StringValue, was: %T`, ownerNameAttribute))
	}

	ownerTypeAttribute, ok := attributes["owner_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner_type is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	ownerTypeVal, ok := ownerTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner_type expected to be basetypes.StringValue, was: %T`, ownerTypeAttribute))
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	return OwnerValue{
		OwnerEmail: ownerEmailVal,
		OwnerId:    ownerIdVal,
		OwnerName:  ownerNameVal,
		OwnerType:  ownerTypeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerValue {
	object, diags := NewOwnerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerValueMust(OwnerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerType) ValueType(ctx context.Context) attr.Value {
	return OwnerValue{}
}

var _ basetypes.ObjectValuable = OwnerValue{}

type OwnerValue struct {
	OwnerEmail basetypes.StringValue `tfsdk:"owner_email"`
	OwnerId    basetypes.StringValue `tfsdk:"owner_id"`
	OwnerName  basetypes.StringValue `tfsdk:"owner_name"`
	OwnerType  basetypes.StringValue `tfsdk:"owner_type"`
	state      attr.ValueState
}

func (v OwnerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["owner_email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["owner_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["owner_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["owner_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.OwnerEmail.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owner_email"] = val

		val, err = v.OwnerId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owner_id"] = val

		val, err = v.OwnerName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owner_name"] = val

		val, err = v.OwnerType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owner_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerValue) String() string {
	return "OwnerValue"
}

func (v OwnerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"owner_email": basetypes.StringType{},
			"owner_id":    basetypes.StringType{},
			"owner_name":  basetypes.StringType{},
			"owner_type":  basetypes.StringType{},
		},
		map[string]attr.Value{
			"owner_email": v.OwnerEmail,
			"owner_id":    v.OwnerId,
			"owner_name":  v.OwnerName,
			"owner_type":  v.OwnerType,
		})

	return objVal, diags
}

func (v OwnerValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.OwnerEmail.Equal(other.OwnerEmail) {
		return false
	}

	if !v.OwnerId.Equal(other.OwnerId) {
		return false
	}

	if !v.OwnerName.Equal(other.OwnerName) {
		return false
	}

	if !v.OwnerType.Equal(other.OwnerType) {
		return false
	}

	return true
}

func (v OwnerValue) Type(ctx context.Context) attr.Type {
	return OwnerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"owner_email": basetypes.StringType{},
		"owner_id":    basetypes.StringType{},
		"owner_name":  basetypes.StringType{},
		"owner_type":  basetypes.StringType{},
	}
}
