// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_settings_reviews

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SettingsReviewsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"is_config_review_required": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether config reviews are required.",
				MarkdownDescription: "Whether config reviews are required.",
			},
			"is_metric_review_required": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether metric reviews are required.",
				MarkdownDescription: "Whether metric reviews are required.",
			},
			"is_metric_review_required_on_verified_only": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether metric reviews are only required for verified metrics.",
				MarkdownDescription: "Whether metric reviews are only required for verified metrics.",
			},
			"is_whn_analysis_only_review_required": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether analysis-only experiment reviews are required. Only applicable to WHN projects.",
				MarkdownDescription: "Whether analysis-only experiment reviews are required. Only applicable to WHN projects.",
			},
			"is_whn_source_review_required": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether metric/assignment/entity property source reviews are required. Only applicable to WHN projects.",
				MarkdownDescription: "Whether metric/assignment/entity property source reviews are required. Only applicable to WHN projects.",
			},
		},
	}
}

type SettingsReviewsModel struct {
	IsConfigReviewRequired               types.Bool `tfsdk:"is_config_review_required"`
	IsMetricReviewRequired               types.Bool `tfsdk:"is_metric_review_required"`
	IsMetricReviewRequiredOnVerifiedOnly types.Bool `tfsdk:"is_metric_review_required_on_verified_only"`
	IsWhnAnalysisOnlyReviewRequired      types.Bool `tfsdk:"is_whn_analysis_only_review_required"`
	IsWhnSourceReviewRequired            types.Bool `tfsdk:"is_whn_source_review_required"`
}
