// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_keys

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func KeysResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(1000),
				},
			},
			"environments": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"key": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"scopes": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"secondary_target_app_ids": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"target_app_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"SERVER",
						"CLIENT",
						"CONSOLE",
						"SCIM",
					),
				},
			},
		},
	}
}

type KeysModel struct {
	Description           types.String `tfsdk:"description"`
	Environments          types.List   `tfsdk:"environments"`
	Key                   types.String `tfsdk:"key"`
	Scopes                types.List   `tfsdk:"scopes"`
	SecondaryTargetAppIds types.List   `tfsdk:"secondary_target_app_ids"`
	TargetAppId           types.String `tfsdk:"target_app_id"`
	Type                  types.String `tfsdk:"type"`
}
