// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_settings_teams

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SettingsTeamsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"require_teams_on_configs": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether a team is required on each new config.",
				MarkdownDescription: "Whether a team is required on each new config.",
			},
		},
	}
}

type SettingsTeamsModel struct {
	RequireTeamsOnConfigs types.Bool `tfsdk:"require_teams_on_configs"`
}
