// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_settings_roles

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SettingsRolesResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"default_project_role": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the default project role.",
				MarkdownDescription: "The name of the default project role.",
			},
		},
	}
}

type SettingsRolesModel struct {
	DefaultProjectRole types.String `tfsdk:"default_project_role"`
}
