provider:
  name: statsig

resources:
  keys:
    read:
      path: /console/v1/keys/{id}
      method: GET
    create:
      path: /console/v1/keys
      method: POST
    update:
      path: /console/v1/keys/{id}
      method: PATCH
    delete:
      path: /console/v1/keys/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: key

  gate:
    read:
      path: /console/v1/gates/{id}
      method: GET
    create:
      path: /console/v1/gates
      method: POST
    update:
      path: /console/v1/gates/{id}
      method: PATCH
    delete:
      path: /console/v1/gates/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  experiment:
    read:
      path: /console/v1/experiments/{id}
      method: GET
    create:
      path: /console/v1/experiments
      method: POST
    update:
      path: /console/v1/experiments/{id}
      method: PATCH
    delete:
      path: /console/v1/experiments/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  dynamic_config:
    read:
      path: /console/v1/dynamic_configs/{id}
      method: GET
    create:
      path: /console/v1/dynamic_configs
      method: POST
    update:
      path: /console/v1/dynamic_configs/{id}
      method: PATCH
    delete:
      path: /console/v1/dynamic_configs/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  entity_property:
    read:
      path: /console/v1/experiments/entity_property/{name}
      method: GET
    create:
      path: /console/v1/experiments/entity_properties
      method: POST
    update:
      path: /console/v1/experiments/entity_property/{name}
      method: POST
    delete:
      path: /console/v1/experiments/entity_property/{name}
      method: DELETE
    schema:
      ignores:
        - message
        - data

  qualifying_event:
    read:
      path: /console/v1/experiments/qualifying_events/{name}
      method: GET
    create:
      path: /console/v1/experiments/qualifying_events
      method: POST
    update:
      path: /console/v1/experiments/qualifying_events/{name}
      method: POST
    delete:
      path: /console/v1/experiments/qualifying_events/{name}
      method: DELETE
    schema:
      ignores:
        - message
        - data

  metric_source:
    read:
      path: /console/v1/metrics/metric_source/{name}
      method: GET
    create:
      path: /console/v1/metrics/metric_source
      method: POST
    update:
      path: /console/v1/metrics/metric_source/{name}
      method: POST
    delete:
      path: /console/v1/metrics/metric_source/{name}
      method: DELETE
    schema:
      ignores:
        - message
        - data

  metric:
    read:
      path: /console/v1/metrics/{id}
      method: GET
    create:
      path: /console/v1/metrics
      method: POST
    update:
      path: /console/v1/metrics/{id}
      method: POST
    delete:
      path: /console/v1/metrics/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data

  tag:
    read:
      path: /console/v1/tags/{id}
      method: GET
    create:
      path: /console/v1/tags
      method: POST
    update:
      path: /console/v1/tags/{id}
      method: PATCH
    delete:
      path: /console/v1/tags/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  role:
    read:
      path: /console/v1/roles/{id}
      method: GET
    create:
      path: /console/v1/roles
      method: POST
    update:
      path: /console/v1/roles/{id}
      method: PATCH
    delete:
      path: /console/v1/roles/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  environments:
    read:
      path: /console/v1/environments
      method: GET
    create:
      path: /console/v1/environments
      method: POST
    update:
      path: /console/v1/environments
      method: POST
    schema:
      ignores:
        - message
        - data

  settings_roles:
    read:
      path: /console/v1/settings/roles
      method: GET
    create:
      path: /console/v1/settings/roles
      method: POST
    update:
      path: /console/v1/settings/roles
      method: POST
    schema:
      ignores:
        - message
        - data

  settings_reviews:
    read:
      path: /console/v1/settings/reviews
      method: GET
    create:
      path: /console/v1/settings/reviews
      method: POST
    update:
      path: /console/v1/settings/reviews
      method: POST
    schema:
      ignores:
        - message
        - data

  settings_teams:
    read:
      path: /console/v1/settings/teams
      method: GET
    create:
      path: /console/v1/settings/teams
      method: POST
    update:
      path: /console/v1/settings/teams
      method: POST
    schema:
      ignores:
        - message
        - data
