
provider:
  name: statsig

resources:
  keys:
    read:
      path: /console/v1/keys/{id}
      method: GET
    create:
      path: /console/v1/keys
      method: POST
    update:
      path: /console/v1/keys/{id}
      method: PATCH
    delete:
      path: /console/v1/keys/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: key

  gate:
    read:
      path: /console/v1/gates/{id}
      method: GET
    create:
      path: /console/v1/gates
      method: POST
    update:
      path: /console/v1/gates/{id}
      method: PATCH
    delete:
      path: /console/v1/gates/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name

  experiment:
    read:
      path: /console/v1/experiments/{id}
      method: GET
    create:
      path: /console/v1/experiments
      method: POST
    update:
      path: /console/v1/experiments/{id}
      method: PATCH
    delete:
      path: /console/v1/experiments/{id}
      method: DELETE
    schema:
      ignores:
        - message
        - data
      attributes:
        aliases:
          id: name
