// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_settings_project

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SettingsProjectResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"default_unit_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The default unit ID type of the project for newly created gates, experiments, and metrics. If not provided, there will be no default unit type.",
				MarkdownDescription: "The default unit ID type of the project for newly created gates, experiments, and metrics. If not provided, there will be no default unit type.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the project.",
				MarkdownDescription: "The name of the project.",
			},
			"visibility": schema.StringAttribute{
				Required:            true,
				Description:         "The visibility type of the project.",
				MarkdownDescription: "The visibility type of the project.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"OPEN",
						"CLOSED",
						"EXTERNAL",
					),
				},
			},
		},
	}
}

type SettingsProjectModel struct {
	DefaultUnitType types.String `tfsdk:"default_unit_type"`
	Name            types.String `tfsdk:"name"`
	Visibility      types.String `tfsdk:"visibility"`
}
