// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_unit_id_type

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UnitIdTypeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the unit id type.",
				MarkdownDescription: "The description of the unit id type.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the unit id type.",
				MarkdownDescription: "The name of the unit id type.",
			},
		},
	}
}

type UnitIdTypeModel struct {
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
}
