// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_role

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RoleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the role.",
				MarkdownDescription: "The name of the role.",
			},
			"permissions": schema.MapAttribute{
				ElementType:         types.BoolType,
				Required:            true,
				Description:         "The permissions of the role.",
				MarkdownDescription: "The permissions of the role.",
			},
		},
	}
}

type RoleModel struct {
	Name        types.String `tfsdk:"name"`
	Permissions types.Map    `tfsdk:"permissions"`
}
