name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  merge_group:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Run Acceptance Tests
        run: |
          make testacc
        env:
          statsig_console_key: ${{ secrets.CONSOLE_API_KEY }}
          statsig_whn_console_key: ${{ secrets.WHN_CONSOLE_API_KEY }}
