name: Test Project Setup

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  setup:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: "1.21"

      - name: Setup Test Projects
        run: |
          make setup-test-projects
        env:
          statsig_server_key: ${{ secrets.SERVER_SDK_KEY }}
